### ISSUE TITLE
Only Wikipedia!

### ISSUE THREAD

**Issue by Aubreymcfato** [ragesoss/coursestats#1]
Is it difficult to generalize the script to other projects (Wikisource, Wikiquote, Wikidata)?

**Comment by ragesoss** [comment]
The view data gets pulled from stats.grok.se, which only provides Wikipedia pageview data.

The articles edited portion of it (for individual users, and the few non-Wikipedia projects that use course pages) would be pretty easy to generalize, though.

**Comment by Aubreymcfato** [comment]
> The articles edited portion of it (for individual users, and the few non-Wikipedia projects that use course pages) would be pretty easy to generalize, though.

Yes! That is what interest me :-) 
We're doing several editathon with Wikisource, so it's useful for education purposes.

**Comment by ragesoss** [comment]
No promises, but I'll see if I can update it. Can you point me to a page about one of these editathons, so I have an idea of what you're trying to do exactly?

**Comment by ragesoss** [comment]
Done! Now you can run this on wikisource and other projects.

**Comment by Aubreymcfato** [comment]
Love you, man :-)
